# Generated by Django 5.2.17 on 2026-09-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('partial', 'Partielle'), ('received', 'Reçue'), ('cancelled', 'Annulée')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='products.product')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereceipt')),
            ],
            options={
                'unique_together': {('purchase_receipt', 'product')},
            },
        ),
    ]
