# Generated by Django 5.2.17 on 2026-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasereceipt_purchasereceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='handling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
