# Generated by Django 5.2.17 on 2026-09-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransfer'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('items_per_carton', models.PositiveIntegerField(default=1)),
                ('qr_code', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartons', to='inventory.inventorylocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartons', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
