# Generated by Django 5.2.17 on 2026-09-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
