# Generated by Django 5.2.17 on 2026-09-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_qr_code'),
        ('suppliers', '0002_exchangerate_supplierimport_supplierimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sale',
            name='external_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_sales', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
