# Generated by Django 5.2.17 on 2026-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('purchase_order', 'Commande fournisseur'), ('supplier_file', 'Fichier fournisseur'), ('admin', 'Administratif')], default='invoice', max_length=40)),
                ('file_name', models.CharField(blank=True, default='', max_length=200)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('related_model', models.CharField(blank=True, default='', max_length=80)),
                ('related_id', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé'), ('deleted', 'Supprimé')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
