from django.urls import include, path
from suppliers.views import SupplierImportConfirmView, SupplierImportView
from purchases.views import (
    AcquisitionCostDetailView,
    AcquisitionCostListView,
    PurchaseOrderActionView,
    PurchaseOrderDetailView,
    PurchaseOrderListCreateView,
    PurchaseReceiptDetailView,
    PurchaseReceiptListCreateView,
    PurchaseReceiptValidateView,
)
from inventory.views import (
    CartonDetailView,
    CartonListCreateView,
    CartonQrView,
    InventoryLocationDetailView,
    InventoryLocationListCreateView,
    InventoryLocationStockView,
    QrResolveView,
    StockItemListView,
    StockMovementDetailView,
    StockMovementListCreateView,
    StockTransferActionView,
    StockTransferDetailView,
    StockTransferListCreateView,
)
from payments.views import CreditListView
from core.views import (
    AdvancedReportingView,
    AppSettingDetailView,
    AppSettingListCreateView,
    AuditLogListView,
    CashTransactionsView,
    CashView,
    CashflowSummaryView,
    CompanyView,
    DashboardSummaryView,
    FinancialSummaryView,
    GlobalSearchView,
)
from notifications.views import MessageHistoryView
from core.sync import SyncView


urlpatterns = [
    path('company/', CompanyView.as_view(), name='company'),
    path('dashboard/', DashboardSummaryView.as_view(), name='dashboard-summary'),
    path('audit/', AuditLogListView.as_view(), name='audit-log-list'),
    path('search/', GlobalSearchView.as_view(), name='global-search'),
    path('inventory/', StockItemListView.as_view(), name='inventory-stock'),
    path('locations/', InventoryLocationListCreateView.as_view(), name='location-list-create'),
    path('locations/<int:pk>/', InventoryLocationDetailView.as_view(), name='location-detail'),
    path('locations/<int:pk>/stock/', InventoryLocationStockView.as_view(), name='location-stock'),
    path('cartons/', CartonListCreateView.as_view(), name='carton-list-create'),
    path('cartons/<int:pk>/', CartonDetailView.as_view(), name='carton-detail'),
    path('stock-movements/', StockMovementListCreateView.as_view(), name='stock-movements'),
    path('stock-movements/<int:pk>/', StockMovementDetailView.as_view(), name='stock-movement-detail'),
    path('receipts/', PurchaseReceiptListCreateView.as_view(), name='receipt-list-create'),
    path('receipts/<int:pk>/', PurchaseReceiptDetailView.as_view(), name='receipt-detail'),
    path('acquisition-costs/', AcquisitionCostListView.as_view(), name='acquisition-cost-list'),
    path('acquisition-costs/<int:pk>/', AcquisitionCostDetailView.as_view(), name='acquisition-cost-detail'),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('purchase-imports/', SupplierImportView.as_view(), name='purchase-import-create'),
    path('purchase-imports/<int:pk>/confirm/', SupplierImportConfirmView.as_view(), name='purchase-import-confirm'),
    path('receipts/<int:pk>/validate/', PurchaseReceiptValidateView.as_view(), name='receipt-validate'),
    path('purchase-orders/', PurchaseOrderListCreateView.as_view(), name='purchase-order-list-create'),
    path('purchase-orders/<int:pk>/', PurchaseOrderDetailView.as_view(), name='purchase-order-detail'),
    path('purchase-orders/<int:pk>/<str:action>/', PurchaseOrderActionView.as_view(), name='purchase-order-action'),
    path('transfers/', StockTransferListCreateView.as_view(), name='transfer-list-create'),
    path('transfers/<int:pk>/', StockTransferDetailView.as_view(), name='transfer-detail'),
    path('transfers/<int:pk>/<str:action>/', StockTransferActionView.as_view(), name='transfer-action'),
    path('cartons/<int:pk>/qr/', CartonQrView.as_view(), name='carton-qr'),
    path('qr/resolve/', QrResolveView.as_view(), name='qr-resolve'),
    path('credits/', CreditListView.as_view(), name='credit-list'),
    path('cash/', CashView.as_view(), name='cash-summary'),
    path('cashflow/', CashflowSummaryView.as_view(), name='cashflow-summary'),
    path('cash/transactions/', CashTransactionsView.as_view(), name='cash-transactions'),
    path('financial-summary/', FinancialSummaryView.as_view(), name='financial-summary'),
    path('settings/', AppSettingListCreateView.as_view(), name='app-setting-list-create'),
    path('settings/<int:pk>/', AppSettingDetailView.as_view(), name='app-setting-detail'),
    path('reports/sales/', AdvancedReportingView.as_view(), name='sales-report'),
    path('reports/inventory/', AdvancedReportingView.as_view(), name='inventory-report'),
    path('reports/credits/', AdvancedReportingView.as_view(), name='credit-report'),
    path('reports/purchases/', AdvancedReportingView.as_view(), name='purchase-report'),
    path('reports/finance/', AdvancedReportingView.as_view(), name='finance-report'),
    path('messages/', MessageHistoryView.as_view(), name='message-history'),
    path('sync/', SyncView.as_view(), name='sync'),
    path('customers/', include('customers.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('payments/', include('payments.urls')),
    path('notifications/', include('notifications.urls')),
    path('expenses/', include('expenses.urls')),
    path('invoices/', include('invoices.urls')),
    path('documents/', include('documents.urls')),
    path('core/', include('core.urls')),
]
