# Generated by Django 5.2.17 on 2026-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyboard_layout',
            field=models.CharField(choices=[('fr', 'Français'), ('us', 'US')], default='fr', max_length=10),
        ),
    ]
