# Generated by Django 5.2.17 on 2026-09-12 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(default='USD', max_length=10)),
                ('target_currency', models.CharField(default='GNF', max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('source_currency', 'target_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='SupplierImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('parsed', 'Traité'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='parsed', max_length=20)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_imports', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=220)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('matched_product', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('supplier_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='suppliers.supplierimport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
