# Generated by Django 5.2.17 on 2026-09-18 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasereceipt_handling_cost_and_more'),
        ('suppliers', '0002_exchangerate_supplierimport_supplierimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierimport',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_imports', to='purchases.purchaseorder'),
        ),
    ]
